package com.kids.servent.message;

public enum MessageType {
	POISON,
	TRANSACTION,
	AB_SNAPSHOT_REQUEST,
	AB_SNAPSHOT_RESPONSE,
	AV_MARKER,
	AV_DONE,
	AV_TERMINATE,
	CC_SNAPSHOT_REQUEST,
	CC_SNAPSHOT_RESPONSE,
	CC_RESUME
}
